backend:
  name: github
  repo: <OWNER>/<REPO>
  branch: main
  base_url: https://<OAUTH-HOST>
  auth_endpoint: <OAUTH-PATH>
media_folder: "public/uploads"
public_folder: "/uploads" # For project pages, set to "/<REPO>/uploads"
site_url: https://aneggi.it/
publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "SEO Title", name: "seoTitle", widget: "string", required: false }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Updated Date", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "publications"
    label: "Publications"
    folder: "src/content/publications"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "pubDate", widget: "datetime" }
      - { label: "Venue", name: "venue", widget: "string", required: false }
      - { label: "Link", name: "link", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown", required: false }
